const list = [
  {
    id: 1,
    toggle: false,
    name: "Diamond Earring",
  
    originalPrice: 50,
    discount: "50",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/2.webp",
    categorie: "Rings",
    title:
      "Elegant Gold Ring with a Stunning Design, Perfect for Special Occasions",
    price: 45224,
    tag: "New Arrival",
    classic: false,
    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/3.webp",
    ],
    createdAt: "2024-03-01", 
  },
  {
    id: 2,
    toggle: false,
    name: "Diamond Ring",
   
    originalPrice: 50,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/3.webp",
    categorie: "Rings",
    title: "Diamond Ring Crafted with Precision, Offering a Luxurious Look",
    price: 38500,
    tag: "Best Seller",
    classic: false,
    inerimgList: [
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/3.webp",
      "/img/dimondProdcut/4.webp",
    ],
    createdAt: "2024-05-01", 

  },
  {
    id: 3,
    toggle: false,
    name: "Diamond Earring",
   
    originalPrice: 50,
    discount: "50",
    img1: "/img/dimondProdcut/3.webp",
    img2: "/img/dimondProdcut/4.webp",
    categorie: "Rings",
    title:
      "Silver Band Ring with a Minimalist Yet Classy Appeal for Everyday Wear",
    price: 15000,
    tag: "Best Seller",

    classic: true,
    inerimgList: [
      "/img/dimondProdcut/3.webp",
      "/img/dimondProdcut/4.webp",
      "/img/dimondProdcut/5.webp",
    ],

  },
  {
    id: 4,
    toggle: false,
    name: "Gold Plated Ring",
 
    originalPrice: 60,
    discount: "30",
    img1: "/img/dimondProdcut/4.webp",
    img2: "/img/dimondProdcut/5.webp",
    categorie: "Rings",
    title: "Gold Plated Ring with a Unique and Timeless Design",
    price: 32000,
    tag: "Best Seller",
    classic: true,
    inerimgList: [
      "/img/dimondProdcut/4.webp",
      "/img/dimondProdcut/5.webp",
      "/img/dimondProdcut/6.webp",
    ],
    createdAt: "2024-01-05", 

  },
  {
    id: 5,
    toggle: false,
    name: "Platinum Engagement Ring",
    originalPrice: 75,
    discount: "33",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/6.webp",
    categorie: "Rings",
    title: "Platinum Engagement Ring with a Brilliant Diamond Setting",
    price: 55000,
    tag: "Best Seller",
    classic: true,
    inerimgList: [
      "/img/dimondProdcut/5.webp",
      "/img/dimondProdcut/6.webp",
      "/img/dimondProdcut/7.webp",
    ],
    createdAt: "2024-01-05", 

  },
  {
    id: 6,
    toggle: false,
    name: "Sapphire Ring",
    price: 48,
    originalPrice: 70,
    discount: "31",
    img1: "/img/dimondProdcut/6.webp",
    img2: "/img/dimondProdcut/7.webp",
    categorie: "Rings",
    title: "Sapphire Gemstone Ring with Exquisite Craftsmanship",
    price: 42000,
    tag: "New Arrival",
    classic: true,
    inerimgList: [
      "/img/dimondProdcut/6.webp",
      "/img/dimondProdcut/7.webp",
      "/img/dimondProdcut/8.webp",
    ],
    createdAt: "2024-01-05", 

  },
  {
    id: 7,
    toggle: false,
    name: "Rose Gold Promise Ring",
    price: 28000, // Removed duplicate price key
    originalPrice: 55,
    discount: "36",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Rings",
    title: "Rose Gold Promise Ring with a Delicate and Romantic Appeal",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-01-05", // Added createdAt field
    inerimgList: [
      "/img/dimondProdcut/7.webp",
      "/img/dimondProdcut/8.webp",
      "/img/dimondProdcut/9.webp",
    ],
  },
  {
    id: 8,
    toggle: false,
    name: "Classic Wedding Band",
    price: 35000, // Removed duplicate price key
    originalPrice: 65,
    discount: "38",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Rings",
    title: "Classic Wedding Band with a Simple Yet Elegant Finish",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-01-06", // Added createdAt field
    inerimgList: [
      "/img/dimondProdcut/7.webp",
      "/img/dimondProdcut/8.webp",
      "/img/dimondProdcut/9.webp",
    ],
  },
  {
    id: 9,
    toggle: false,
    name: "Heart-Shaped Pendant",
    price: 19999,
    originalPrice: 40000,
    discount: "50",
    img1: "/img/dimondProdcut/9.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Pendant",
    title: "Heart-Shaped Pendant with a Romantic Touch, Perfect as a Gift",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-01-07", // Added createdAt field
    inerimgList: [
      "/img/dimondProdcut/9.webp",
      "/img/dimondProdcut/10.webp",
      "/img/dimondProdcut/11.webp",
    ],
  },
  {
    id: 10,
    toggle: false,
    name: "Gold Pendant",
    price: 24999,
    originalPrice: 50000,
    discount: "50",
    img1: "/img/dimondProdcut/10.webp",
    img2: "/img/dimondProdcut/11.webp",
    categorie: "Pendant",
    title: "Gold Pendant with a Timeless Design, Blending Elegance and Style",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-01-08", // Added createdAt field
    inerimgList: [
      "/img/dimondProdcut/11.webp",
      "/img/dimondProdcut/12.webp",
      "/img/dimondProdcut/13.webp",
    ],
  },
  {
    id: 11,
    toggle: false,
    name: "Platinum Pendant",
    price: 32000,
    originalPrice: 64000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Pendant",
    title: "Platinum Pendant with a Unique Pattern, Enhancing Your Grace",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-02-08", // Added createdAt field

    inerimgList: [
      "/img/dimondProdcut/11.webp",
      "/img/dimondProdcut/12.webp",
      "/img/dimondProdcut/13.webp",
    ],
  },
  {
    id: 12,
    toggle: false,
    name: "Diamond Cross Pendant",
    price: 28500,
    originalPrice: 57000,
    discount: "50",
    img1: "/img/dimondProdcut/12.webp",
    img2: "/img/dimondProdcut/13.webp",
    categorie: "Pendant",
    title: "Elegant Diamond Cross Pendant, A Symbol of Faith and Beauty",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-04-08", // Added createdAt field

    inerimgList: [
      "/img/dimondProdcut/12.webp",
      "/img/dimondProdcut/13.webp",
      "/img/dimondProdcut/14.webp",
    ],
  },
  {
    id: 13,
    toggle: false,
    name: "Emerald Pendant",
    price: 35000,
    originalPrice: 70000,
    discount: "50",
    img1: "/img/dimondProdcut/14.webp",
    img2: "/img/dimondProdcut/15.webp",
    categorie: "Pendant",
    title: "Emerald Pendant with a Classic Design, Perfect for Any Occasion",
    tag: "Special Offer",
    classic: true,
    createdAt: "2024-05-11", // Added createdAt field

    inerimgList: [
      "/img/dimondProdcut/14.webp",
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
    ],
  },
  {
    id: 14,
    toggle: false,
    name: "Sapphire Pendant",
    price: 41000,
    originalPrice: 82000,
    discount: "50",
    img1: "/img/dimondProdcut/15.webp",
    img6: "/img/dimondProdcut/16.webp",
    categorie: "Pendant",
    title: "Sapphire Pendant with an Exquisite Royal Look",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-01-11", // Added createdAt field

    inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 15,
    toggle: false,
    name: "Ruby Pendant",
    price: 38000,
    originalPrice: 76000,
    discount: "50",
    img1: "/img/dimondProdcut/16.webp",
    img2: "/img/dimondProdcut/16hover.webp",
    categorie: "Pendant",
    title: "Ruby Pendant Featuring a Bold and Eye-Catching Design",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-02-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 16,
    toggle: false,
    name: "Infinity Symbol Pendant",
    price: 29500,
    originalPrice: 59000,
    discount: "50",
    img1: "/img/dimondProdcut/17.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Pendant",
    title: "Infinity Symbol Pendant Representing Endless Love and Elegance",
    tag: "New Arrival",
    classic: true,
    createdAt: "2023-01-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 17,
    toggle: false,
    name: "Heart-Shaped Pendant",
    price: 19999,
    originalPrice: 40000,
    discount: "50",
    img1: "/img/dimondProdcut/4.webp",
    img2: "/img/dimondProdcut/3.webp",
    categorie: "Pendant",
    title: "Heart-Shaped Pendant with a Romantic Touch, Perfect as a Gift",
    tag: "Special Offer",
    classic: true,
    createdAt: "2022-11-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 18,
    toggle: false,
    name: "Gold Pendant",
    price: 24999,
    originalPrice: 50000,
    discount: "50",
    img1: "/img/dimondProdcut/2.webp",
    img2: "/img/dimondProdcut/4.webp",
    categorie: "Pendant",
    title: "Gold Pendant with a Timeless Design, Blending Elegance and Style",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-08-16", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 19,
    toggle: false,
    name: "Platinum Pendant",
    price: 32000,
    originalPrice: 64000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/6.webp",
    categorie: "Pendant",
    title: "Platinum Pendant with a Unique Pattern, Enhancing Your Grace",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-07-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 20,
    toggle: false,
    name: "Diamond Cross Pendant",
    price: 28500,
    originalPrice: 57000,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Pendant",
    title: "Elegant Diamond Cross Pendant, A Symbol of Faith and Beauty",
    tag: "Special Offer",
    classic: true,
    createdAt: "2024-08-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 21,
    toggle: false,
    name: "Emerald Pendant",
    price: 35000,
    originalPrice: 70000,
    discount: "50",
    img1: "/img/dimondProdcut/9.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Pendant",
    title: "Emerald Pendant with a Classic Design, Perfect for Any Occasion",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-02-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 22,
    toggle: false,
    name: "Sapphire Pendant",
    price: 41000,
    originalPrice: 82000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Pendant",
    title: "Sapphire Pendant with an Exquisite Royal Look",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-08-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 23,
    toggle: false,
    name: "Ruby Pendant",
    price: 38000,
    originalPrice: 76000,
    discount: "50",
    img1: "/img/dimondProdcut/24.webp",
    img2: "/img/dimondProdcut/24hover.webp",
    categorie: "Pendant",
    title: "Ruby Pendant Featuring a Bold and Eye-Catching Design",
    tag: "Special Offer",
    classic: true,
    createdAt: "2024-01-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 24,
    toggle: false,
    name: "Infinity Symbol Pendant",
    price: 29500,
    originalPrice: 59000,
    discount: "50",
    img1: "/img/dimondProdcut/25.webp",
    img2: "/img/dimondProdcut/25hover.webp",
    categorie: "Pendant",
    title: "Infinity Symbol Pendant Representing Endless Love and Elegance",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-05-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 25,
    toggle: false,
    name: "Heart-Shaped Pendant",
    price: 19999,
    originalPrice: 40000,
    discount: "50",
    img1: "/img/dimondProdcut/26.webp",
    img2: "/img/dimondProdcut/26hover.webp",
    categorie: "Pendant",
    title: "Heart-Shaped Pendant with a Romantic Touch, Perfect as a Gift",
    tag: "New Arrival",
    classic: true,
        createdAt: "2024-01-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 26,
    toggle: false,
    name: "Gold Pendant",
    price: 24999,
    originalPrice: 50000,
    discount: "50",
    img1: "/img/dimondProdcut/27.webp",
    img2: "/img/dimondProdcut/27hover.webp",
    categorie: "Pendant",
    title: "Gold Pendant with a Timeless Design, Blending Elegance and Style",
    tag: "Special Offer",
    classic: true,
        createdAt: "2024-01-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 27,
    toggle: false,
    name: "Platinum Pendant",
    price: 32000,
    originalPrice: 64000,
    discount: "50",
    img1: "/img/dimondProdcut/28.webp",
    img2: "/img/dimondProdcut/32hover.webp",
    categorie: "Pendant",
    title: "Platinum Pendant with a Unique Pattern, Enhancing Your Grace",
    tag: "New Arrival",
    classic: true,
        createdAt: "2024-01-11", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 28,
    toggle: false,
    name: "Diamond Cross Pendant",
    price: 28500,
    originalPrice: 57000,
    discount: "50",
    img1: "/img/dimondProdcut/4.webp",
    img2: "/img/dimondProdcut/4hover.webp",
    categorie: "Pendant",
    title: "Elegant Diamond Cross Pendant, A Symbol of Faith and Beauty",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-04-18", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 29,
    toggle: false,
    name: "Emerald Pendant",
    price: 35000,
    originalPrice: 70000,
    discount: "50",
    img1: "/img/dimondProdcut/18.webp",
    img2: "/img/dimondProdcut/19.webp",
    categorie: "Pendant",
        createdAt: "2024-04-18", // Added createdAt field

    title: "Emerald Pendant with a Classic Design, Perfect for Any Occasion",
    tag: "New Arrival",
    classic: true,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 30,
    toggle: false,
    name: "Sapphire Pendant",
    price: 41000,
    originalPrice: 82000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/5hover.webp",
    categorie: "Pendant",
    title: "Sapphire Pendant with an Exquisite Royal Look",
    tag: "Best Seller",
        createdAt: "2024-04-18", // Added createdAt field

    classic: true,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },

  {
    id: 31,
    toggle: false,
    name: "Ruby Pendant",
    price: 38000,
    originalPrice: 76000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Pendant",
    title: "Ruby Pendant Featuring a Bold and Eye-Catching Design",
    tag: "Best Seller",
        createdAt: "2024-04-18", // Added createdAt field

    classic: false,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 32,
    toggle: false,
    name: "Infinity Symbol Pendant",
    price: 29500,
    originalPrice: 59000,
    discount: "50",
    img1: "/img/dimondProdcut/12.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Pendant",
    title: "Infinity Symbol Pendant Representing Endless Love and Elegance",
    tag: "New Arrival",
        createdAt: "2024-04-18", // Added createdAt field

    classic: false,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 33,
    toggle: false,
    name: "Diamond Bracelet",
    price: 55000,
    originalPrice: 110000,
    discount: "50",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Bracelets",
    title: "Diamond Bracelet with Exquisite Detailing for an Elegant Look",
    tag: "Special Offer",
    classic: false,
        createdAt: "2024-04-18", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 34,
    toggle: false,
    name: "Gold Bracelet",
    price: 42000,
    originalPrice: 84000,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/7hover.webp",
    categorie: "Bracelets",
    title:
      "Gold Bracelet with an Intricate Design, Adding Luxury to Your Style",
    tag: "Best Seller",
    classic: false,
        createdAt: "2024-04-18", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 35,
    toggle: false,
    name: "Silver Charm Bracelet",
    price: 18500,
    originalPrice: 37000,
    discount: "50",
    img1: "/img/dimondProdcut/6.webp",
    img2: "/img/dimondProdcut/6hover.webp",
    categorie: "Bracelets",
    title: "Silver Charm Bracelet with Delicate Engravings for a Trendy Appeal",
    tag: "New Arrival",
    classic: false,
        createdAt: "2024-04-18", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },

  {
    id: 36,
    toggle: false,
    name: "Platinum Cuff Bracelet",
    price: 60000,
    originalPrice: 120000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/5hover.webp",
    categorie: "Bracelets",
    title: "Platinum Cuff Bracelet with a Bold and Modern Appeal",
    tag: "New Arrival",
    classic: false,
        createdAt: "2024-04-18", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 37,
    toggle: false,
    name: "Ruby-Studded Bracelet",
    price: 49500,
    originalPrice: 99000,
    discount: "50",
    img1: "/img/dimondProdcut/2.webp",
    img2: "/img/dimondProdcut/2hover.webp",
    categorie: "Bracelets",
    title: "Elegant Ruby-Studded Bracelet with a Royal Aesthetic",
    tag: "New Arrival",

        createdAt: "2024-04-18", // Added createdAt field

    classic: false,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 38,
    toggle: false,
    name: "Sapphire Tennis Bracelet",
    price: 68000,
    originalPrice: 136000,
    discount: "50",
    img1: "/img/dimondProdcut/1.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Bracelets",
    title: "Sapphire Tennis Bracelet Designed for Luxury and Sophistication",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 39,
    toggle: false,
    name: "Emerald Beaded Bracelet",
    price: 32000,
    originalPrice: 64000,
    discount: "50",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Bracelets",
    title: "Emerald Beaded Bracelet with a Unique and Trendy Look",
    tag: "Best Seller",
    classic: false,    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 40,
    toggle: false,
    name: "Infinity Knot Bracelet",
    price: 27000,
    originalPrice: 54000,
    discount: "50",
    img1: "/img/dimondProdcut/4.webp",
    img2: "/img/dimondProdcut/11.webp",
    categorie: "Bracelets",
    title: "Infinity Knot Bracelet Symbolizing Eternal Love and Strength",
    tag: "Best Seller",
    classic: false,    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },

  {
    id: 41,
    toggle: false,
    name: "Traditional Gold Bangles",
    price: 68000,
    originalPrice: 136000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Bangles",
    title:
      "Traditional Gold Bangles with an Ethnic Touch, Perfect for Festive Wear",
    tag: "New Arrival",
    classic: true,    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 42,
    toggle: false,
    name: "Diamond Studded Bangles",
    price: 75000,
    originalPrice: 150000,
    discount: "50",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/16.webp",
    categorie: "Bangles",
    title:
      "Diamond Studded Bangles for a Royal Look, Blending Tradition with Luxury",
    tag: "Best Seller",
    classic: true,    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 43,
    toggle: false,
    name: "Antique Bangles",
    price: 49000,
    originalPrice: 98000,
    discount: "50",
    img1: "/img/dimondProdcut/2.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Bangles",
    title:
      "Antique Bangles with an Old-World Charm, Showcasing Fine Craftsmanship",
    tag: "Special Offer",
    classic: true,    createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 44,
    toggle: false,
    name: "Kundan Bangles",
    price: 72000,
    originalPrice: 144000,
    discount: "50",
    img1: "/img/dimondProdcut/2.webp",
    img2: "/img/dimondProdcut/3.webp",
    categorie: "Bangles",
    title:
      "Kundan Bangles with Intricate Detailing, Perfect for Grand Occasions",
    tag: "New Arrival",
    classic: true,   
     createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 45,
    toggle: false,
    name: "Platinum Bangles",
    price: 85000,
    originalPrice: 170000,
    discount: "50",
    img1: "/img/dimondProdcut/1.webp",
    img2: "/img/dimondProdcut/2.webp",
    categorie: "Bangles",
    title: "Modern Platinum Bangles Offering a Sleek and Sophisticated Look",
    tag: "Best Seller",
    classic: true,  
      createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 46,
    toggle: false,
    name: "Ruby-Embedded Bangles",
    price: 65000,
    originalPrice: 130000,
    discount: "50",
    img1: "/img/dimondProdcut/4.webp",
    img2: "/img/dimondProdcut/5.webp",
    categorie: "Bangles",
    title: "Ruby-Embedded Bangles with a Regal Design, Enhancing Elegance",
    tag: "Special Offer",
    classic: true, 
       createdAt: "2024-05-14", // Added createdAt field

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 47,
    toggle: false,
    name: "Silver Filigree Bangles",
    price: 42000,
    originalPrice: 84000,
    discount: "50",
    img1: "/img/dimondProdcut/1.webp",
    img2: "/img/dimondProdcut/2.webp",
    categorie: "Bangles" , // Added createdAt field
    createdAt: "2024-05-14", // Added createdAt field

    title:
      "Silver Filigree Bangles with Artistic Detailing, A Timeless Classic",
    tag: "New Arrival",
    classic: true,
  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 48,
    toggle: false,
    name: "Pearl Inlay Bangles",
    price: 58000,
    originalPrice: 116000,
    discount: "50",
    img1: "/img/dimondProdcut/1.webp",
    img2: "/img/dimondProdcut/2.webp",
    categorie: "Bangles",
    createdAt: "2024-07-14", // Added createdAt field

    title:
      "Pearl Inlay Bangles with a Soft Elegance, Ideal for Graceful Attire",
    tag: "New Arrival",
  },
  {
    id: 49,
    toggle: false,
    name: "Traditional Gold Bangles",
    price: 68000,
    originalPrice: 136000,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Bangles",
    title:
      "Traditional Gold Bangles with an Ethnic Touch, Perfect for Festive Wear",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-07-14", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 50,
    toggle: false,
    name: "Diamond Studded Bangles",
    price: 75000,
    originalPrice: 150000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/6.webp",
    categorie: "Bangles",
    title:
      "Diamond Studded Bangles for a Royal Look, Blending Tradition with Luxury",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-07-14", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 52,
    toggle: false,
    name: "Antique Bangles",
    price: 49000,
    originalPrice: 98000,
    discount: "50",
    img1: "/img/dimondProdcut/2.webp",
    img2: "/img/dimondProdcut/3.webp",
    categorie: "Bangles",
    title:
      "Antique Bangles with an Old-World Charm, Showcasing Fine Craftsmanship",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-07-14", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 53,
    toggle: false,
    name: "Kundan Bangles",
    price: 72000,
    originalPrice: 144000,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Bangles",
    title:
      "Kundan Bangles with Intricate Detailing, Perfect for Grand Occasions",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-07-14", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 55,
    toggle: false,
    name: "Platinum Bangles",
    price: 85000,
    originalPrice: 170000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/6.webp",
    categorie: "Bangles",
    title: "Modern Platinum Bangles Offering a Sleek and Sophisticated Look",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-07-14", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 56,
    toggle: false,
    name: "Ruby-Embedded Bangles",
    price: 65000,
    originalPrice: 130000,
    discount: "50",
    img1: "/img/dimondProdcut/3.webp",
    img2: "/img/dimondProdcut/4.webp",
    categorie: "Bangles",
    title: "Ruby-Embedded Bangles with a Regal Design, Enhancing Elegance",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-01-12", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 57,
    toggle: false,
    name: "Silver Filigree Bangles",
    price: 42000,
    originalPrice: 84000,
    discount: "50",
    img1: "/img/dimondProdcut/3.webp",
    img2: "/img/dimondProdcut/4.webp",
    categorie: "Bangles",
    title:
      "Silver Filigree Bangles with Artistic Detailing, A Timeless Classic",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-01-12", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 58,
    toggle: false,
    name: "Pearl Inlay Bangles",
    price: 58000,
    originalPrice: 116000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/1.webp",
    categorie: "Bangles",
    title:
      "Pearl Inlay Bangles with a Soft Elegance, Ideal for Graceful Attire",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-01-12", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 59,
    toggle: false,
    name: "Pearl Necklace",
    price: 37000,
    originalPrice: 74000,
    discount: "50",
    img1: "/img/dimondProdcut/12.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Necklace",
    title: "Pearl Necklace with a Graceful Finish, Ideal for a Classic Look",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-01-12", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 60,
    toggle: false,
    name: "Gold Chain Necklace",
    price: 52000,
    originalPrice: 104000,
    discount: "50",
    img1: "/img/dimondProdcut/16.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Necklace",
    title:
      "Gold Chain Necklace with a Sleek and Modern Design for Everyday Wear",
    tag: "Best Seller",
    classic: true,
    createdAt: "2024-01-12", 

  inerimgList: [
      "/img/dimondProdcut/15.webp",
      "/img/dimondProdcut/16.webp",
      "/img/dimondProdcut/15.webp",
    ],
  },
  {
    id: 61,
    toggle: false,
    name: "Diamond Necklace",
    price: 85000,
    originalPrice: 170000,
    discount: "50",
    img1: "/img/dimondProdcut/15.webp",
    img2: "/img/dimondProdcut/1.webp",
    categorie: "Necklace",
    title:
      "Diamond Necklace with a Luxurious Look, Perfect for Grand Occasions",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-01-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 62,
    toggle: false,
    name: "Kundan Bridal Necklace",
    price: 98000,
    originalPrice: 196000,
    discount: "50",
    img1: "/img/dimondProdcut/14.webp",
    img2: "/img/dimondProdcut/11.webp",
    categorie: "Necklace",
    title: "Kundan Bridal Necklace with an Exquisite and Traditional Design",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 63,
    toggle: false,
    name: "Emerald Pendant Necklace",
    price: 65000,
    originalPrice: 130000,
    discount: "50",
    img1: "/img/dimondProdcut/13.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Necklace",
    title: "Emerald Pendant Necklace, Offering a Rich and Royal Appeal",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 64,
    toggle: false,
    name: "Platinum Choker Necklace",
    price: 72000,
    originalPrice: 144000,
    discount: "50",
    img1: "/img/dimondProdcut/12.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Necklace",
    title: "Platinum Choker Necklace with a Contemporary yet Elegant Design",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 65,
    toggle: false,
    name: "Sapphire Drop Necklace",
    price: 79000,
    originalPrice: 158000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Necklace",
    title: "Sapphire Drop Necklace with a Stunning and Radiant Finish",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 66,
    toggle: false,
    name: "Ruby Studded Necklace",
    price: 89000,
    originalPrice: 178000,
    discount: "50",
    img1: "/img/dimondProdcut/10.webp",
    img2: "/img/dimondProdcut/10hover.webp",
    categorie: "Necklace",
    title: "Ruby Studded Necklace, A Statement Piece for Special Occasions",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 67,
    toggle: false,
    name: "Stud Earrings",
    price: 21000,
    originalPrice: 42000,
    discount: "50",
    img1: "/img/dimondProdcut/9.webp",
    img2: "/img/dimondProdcut/9hover.webp",
    categorie: "Earrings",
    title: "Stud Earrings with a Simple Yet Elegant Design for a Chic Look",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 68,
    toggle: false,
    name: "Hoop Earrings",
    price: 27500,
    originalPrice: 55000,
    discount: "50",
    img1: "/img/dimondProdcut/8.webp",
    img2: "/img/dimondProdcut/9.webp",
    categorie: "Earrings",
    title:
      "Hoop Earrings with a Bold and Stylish Appearance, Perfect for Parties",
    tag: "Special Offer",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 69,
    toggle: false,
    name: "Dangle Earrings",
    price: 36000,
    originalPrice: 72000,
    discount: "50",
    img1: "/img/dimondProdcut/11.webp",
    img2: "/img/dimondProdcut/12.webp",
    categorie: "Earrings",
    title:
      "Dangle Earrings with an Eye-Catching Shine for an Elegant Statement",
    tag: "New Arrival",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 70,
    toggle: false,
    name: "Chandelier Earrings",
    price: 48000,
    originalPrice: 96000,
    discount: "50",
    img1: "/img/dimondProdcut/9.webp",
    img2: "/img/dimondProdcut/10.webp",
    categorie: "Earrings",
    title: "Chandelier Earrings with Intricate Detailing, Perfect for Weddings",
    tag: "Best Seller",
    createdAt: "2024-05-12", 
    classic: false,
    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],

  },
  {
    id: 71,
    toggle: false,
    name: "Pearl Drop Earrings",
    price: 32000,
    originalPrice: 64000,
    discount: "50",
    img1: "/img/dimondProdcut/7.webp",
    img2: "/img/dimondProdcut/8.webp",
    categorie: "Earrings",
    title: "Pearl Drop Earrings with a Soft and Elegant Look for Formal Wear",
    tag: "New Arrival",
    createdAt: "2024-04-12", 

    classic: false,
    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 72,
    toggle: false,
    name: "Gold Huggie Earrings",
    price: 28500,
    originalPrice: 57000,
    discount: "50",
    img1: "/img/dimondProdcut/5.webp",
    img2: "/img/dimondProdcut/6.webp",
    categorie: "Earrings",
    title: "Gold Huggie Earrings Offering a Modern and Minimalist Appeal",
    tag: "Best Seller",
    classic: false,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 73,
    toggle: false,
    name: "Diamond Cluster Earrings",
    price: 75000,
    originalPrice: 150000,
    discount: "50",
    img1: "/img/dimondProdcut/3.webp",
    img2: "/img/dimondProdcut/4.webp",
    categorie: "Earrings",
    title: "Diamond Cluster Earrings with a Sparkling and Luxurious Touch",
    tag: "Special Offer",
    classic: true,
    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
  {
    id: 74,
    toggle: false,
    name: "Sapphire Stud Earrings",
    price: 43000,
    originalPrice: 86000,
    discount: "50",
    img1: "/img/dimondProdcut/1.webp",
    img2: "/img/dimondProdcut/2.webp",
    categorie: "Earrings",
    title: "Sapphire Stud Earrings Adding a Pop of Color to Any Outfit",
    tag: "New Arrival",
    classic: true,
    createdAt: "2024-05-12", 

    inerimgList: [
      "/img/dimondProdcut/1.webp",
      "/img/dimondProdcut/2.webp",
      "/img/dimondProdcut/5.webp",
    ],
  },
];

export default list;











// new 
// const list = [
//   {
//     id: 1,
//     toggle: false,
//     name: "Diamond Earring",
//     price: 38,
//     originalPrice: 50,
//     discount: "50",
//     img1: "/img/dimondProdcut/rings/ring-1.webp",
//     img2: "/img/dimondProdcut/rings/ring-2.webp",
//     categorie: "Rings",
//     title:
//       "Elegant Gold Ring with a Stunning Design, Perfect for Special Occasions",
//     price: 45224,
//     tag: "New Arrival",
//     classic: false,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-1.webp",
//       "/img/dimondProdcut/rings/ring-2.webp",
//       "/img/dimondProdcut/rings/ring-3.webp",
//     ],
//     createdAt: "2024-03-01", 
//   },

//   {
//     id: 2,
//     toggle: false,
//     name: "Diamond Ring",
//     price: 38,
//     originalPrice: 50,
//     discount: "50",
//     img1: "/img/dimondProdcut/rings/ring-2.webp",
//     img2: "/img/dimondProdcut/rings/ring-3.webp",
//     categorie: "Rings",
//     title: "Diamond Ring Crafted with Precision, Offering a Luxurious Look",
//     price: 38500,
//     tag: "Best Seller",
//     classic: false,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-2.webp",
//       "/img/dimondProdcut/rings/ring-3.webp",
//       "/img/dimondProdcut/rings/ring-4.webp",
//     ],
//     createdAt: "2024-05-01", 

//   },
//   {
//     id: 3,
//     toggle: false,
//     name: "Diamond Earring",
//     price: 38,
//     originalPrice: 50,
//     discount: "50",
//     img1: "/img/dimondProdcut/rings/ring-3.webp",
//     img2: "/img/dimondProdcut/rings/ring-4.webp",
//     categorie: "Rings",
//     title:
//       "Silver Band Ring with a Minimalist Yet Classy Appeal for Everyday Wear",
//     price: 15000,
//     tag: "Best Seller",

//     classic: true,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-3.webp",
//       "/img/dimondProdcut/rings/ring-4.webp",
//       "/img/dimondProdcut/rings/ring-5.webp",
//     ],

//   },
//   {
//     id: 4,
//     toggle: false,
//     name: "Gold Plated Ring",
//     price: 42,
//     originalPrice: 60,
//     discount: "30",
//     img1: "/img/dimondProdcut/rings/ring-4.webp",
//     img2: "/img/dimondProdcut/rings/ring-5.webp",
//     categorie: "Rings",
//     title: "Gold Plated Ring with a Unique and Timeless Design",
//     price: 32000,
//     tag: "Best Seller",
//     classic: true,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-4.webp",
//       "/img/dimondProdcut/rings/ring-5.webp",
//       "/img/dimondProdcut/rings/ring-6.webp",
//     ],
//     createdAt: "2024-01-05", 

//   },
//   {
//     id: 5,
//     toggle: false,
//     name: "Platinum Engagement Ring",
//     price: 50,
//     originalPrice: 75,
//     discount: "33",
//     img1: "/img/dimondProdcut/rings/ring-5.webp",
//     img2: "/img/dimondProdcut/rings/ring-6.webp",
//     categorie: "Rings",
//     title: "Platinum Engagement Ring with a Brilliant Diamond Setting",
//     price: 55000,
//     tag: "Best Seller",
//     classic: true,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-5.webp",
//       "/img/dimondProdcut/rings/ring-6.webp",
//       "/img/dimondProdcut/rings/ring-7.webp",
//     ],
//     createdAt: "2024-01-05", 

//   },
//   {
//     id: 6,
//     toggle: false,
//     name: "Sapphire Ring",
//     price: 48,
//     originalPrice: 70,
//     discount: "31",
//     img1: "/img/dimondProdcut/rings/ring-6.webp",
//     img2: "/img/dimondProdcut/rings/ring-7.webp",
//     categorie: "Rings",
//     title: "Sapphire Gemstone Ring with Exquisite Craftsmanship",
//     price: 42000,
//     tag: "New Arrival",
//     classic: true,
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-6.webp",
//       "/img/dimondProdcut/rings/ring-7.webp",
//       "/img/dimondProdcut/rings/ring-8.webp",
//     ],
//     createdAt: "2024-01-05", 

//   },
//   {
//     id: 7,
//     toggle: false,
//     name: "Rose Gold Promise Ring",
//     price: 28000, // Removed duplicate price key
//     originalPrice: 55,
//     discount: "36",
//     img1: "/img/dimondProdcut/rings/ring-7.webp",
//     img2: "/img/dimondProdcut/rings/ring-8.webp",
//     categorie: "Rings",
//     title: "Rose Gold Promise Ring with a Delicate and Romantic Appeal",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-01-05", // Added createdAt field
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-7.webp",
//       "/img/dimondProdcut/rings/ring-8.webp",
//       "/img/dimondProdcut/rings/ring-4.webp",
//     ],
//   },
//   {
//     id: 8,
//     toggle: false,
//     name: "Classic Wedding Band",
//     price: 35000, // Removed duplicate price key
//     originalPrice: 65,
//     discount: "38",
//     img1: "/img/dimondProdcut/rings/ring-7.webp",
//     img2: "/img/dimondProdcut/rings/ring-8.webp",
//     categorie: "Rings",
//     title: "Classic Wedding Band with a Simple Yet Elegant Finish",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-01-06", // Added createdAt field
//     inerimgList: [
//       "/img/dimondProdcut/rings/ring-7.webp",
//       "/img/dimondProdcut/rings/ring-8.webp",
//       "/img/dimondProdcut/rings/ring-7.webp",
//     ],
//   },
//   {
//     id: 9,
//     toggle: false,
//     name: "Heart-Shaped Pendant",
//     price: 19999,
//     originalPrice: 40000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-1.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-2.webp",
//     categorie: "Pendant",
//     title: "Heart-Shaped Pendant with a Romantic Touch, Perfect as a Gift",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-01-07", // Added createdAt field
//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-1.webp",
//       "/img/dimondProdcut/pendent/pendent-2.webp",
//       "/img/dimondProdcut/pendent/pendent-1.webp",
//     ],
//   },
//   {
//     id: 10,
//     toggle: false,
//     name: "Gold Pendant",
//     price: 24999,
//     originalPrice: 50000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-2.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-3.webp",
//     categorie: "Pendant",
//     title: "Gold Pendant with a Timeless Design, Blending Elegance and Style",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-01-08", // Added createdAt field
//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-2.webp",
//       "/img/dimondProdcut/pendent/pendent-3.webp",
//       "/img/dimondProdcut/pendent/pendent-2.webp",
//     ],
//   },
//   {
//     id: 11,
//     toggle: false,
//     name: "Platinum Pendant",
//     price: 32000,
//     originalPrice: 64000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-3.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-4.webp",
//     categorie: "Pendant",
//     title: "Platinum Pendant with a Unique Pattern, Enhancing Your Grace",
//     tag: "New Arrival",
//     classic: true,
//     createdAt: "2024-02-08", // Added createdAt field

//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-3.webp",
//       "/img/dimondProdcut/pendent/pendent-4.webp",
//       "/img/dimondProdcut/pendent/pendent-3.webp",
//     ],
//   },
//   {
//     id: 12,
//     toggle: false,
//     name: "Diamond Cross Pendant",
//     price: 28500,
//     originalPrice: 57000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-4.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-5.webp",
//     categorie: "Pendant",
//     title: "Elegant Diamond Cross Pendant, A Symbol of Faith and Beauty",
//     tag: "Best Seller",
//     classic: true,
//     createdAt: "2024-04-08", // Added createdAt field

//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-4.webp",
//       "/img/dimondProdcut/pendent/pendent-5.webp",
//       "/img/dimondProdcut/pendent/pendent-4.webp",
//     ],
//   },
//   {
//     id: 13,
//     toggle: false,
//     name: "Emerald Pendant",
//     price: 35000,
//     originalPrice: 70000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-5.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-6.webp",
//     categorie: "Pendant",
//     title: "Emerald Pendant with a Classic Design, Perfect for Any Occasion",
//     tag: "Special Offer",
//     classic: true,
//     createdAt: "2024-05-11", // Added createdAt field

//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-5.webp",
//       "/img/dimondProdcut/pendent/pendent-6.webp",
//       "/img/dimondProdcut/pendent/pendent-5.webp",
//     ],
//   },
//   {
//     id: 14,
//     toggle: false,
//     name: "Sapphire Pendant",
//     price: 41000,
//     originalPrice: 82000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-6.webp",
//     img6: "/img/dimondProdcut/pendent/pendnt-7.webp",
//     categorie: "Pendant",
//     title: "Sapphire Pendant with an Exquisite Royal Look",
//     tag: "New Arrival",
//     classic: true,
//     createdAt: "2024-01-11", // Added createdAt field

//     inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-6.webp",
//       "/img/dimondProdcut/pendent/pendent-7.webp",
//       "/img/dimondProdcut/pendent/pendent-6.webp",
//     ],
//   },
//   {
//     id: 15,
//     toggle: false,
//     name: "Ruby Pendant",
//     price: 38000,
//     originalPrice: 76000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-7.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-8.webp",
//     categorie: "Pendant",
//     title: "Ruby Pendant Featuring a Bold and Eye-Catching Design",
//     tag: "Best Seller",
//     classic: true,
//     createdAt: "2024-02-11", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-7.webp",
//       "/img/dimondProdcut/pendent/pendent-8.webp",
//       "/img/dimondProdcut/pendent/pendent-7.webp",
//     ],
//   },
//   {
//     id: 16,
//     toggle: false,
//     name: "Infinity Symbol Pendant ",
//     price: 29500,
//     originalPrice: 59000,
//     discount: "50",
//     img1: "/img/dimondProdcut/pendent/pendent-8.webp",
//     img2: "/img/dimondProdcut/pendent/pendent-9.webp",
//     categorie: "Pendant",
//     title: "Infinity Symbol Pendant Representing Endless Love and Elegance ",
//     tag: "New Arrival",
//     classic: true,
//     createdAt: "2023-01-11", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/pendent/pendent-7.webp",
//       "/img/dimondProdcut/pendent/pendent-8.webp",
//       "/img/dimondProdcut/pendent/pendent-7.webp",
//     ],
//   },
//    {
//     id: 17,
//     toggle: false,
//     name: "Diamond Bracelet",
//     price: 55000,
//     originalPrice: 110000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-1.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-2.webp",
//     categorie: "Bracelets",
//     title: "Diamond Bracelet with Exquisite Detailing for an Elegant Look",
//     tag: "Special Offer",
//     classic: false,
//         createdAt: "2024-04-18", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-1.webp",
//       "/img/dimondProdcut/braclets/braclet-2.webp",
//       "/img/dimondProdcut/braclets/braclet-1.webp",
//     ],
//   },
//   {
//     id: 18,
//     toggle: false,
//     name: "Gold Bracelet",
//     price: 42000,
//     originalPrice: 84000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-2.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-3.webp",
//     categorie: "Bracelets",
//     title:
//       "Gold Bracelet with an Intricate Design, Adding Luxury to Your Style",
//     tag: "Best Seller",
//     classic: false,
//         createdAt: "2024-04-18", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-2.webp",
//       "/img/dimondProdcut/braclets/braclet-3.webp",
//       "/img/dimondProdcut/braclets/braclet-2.webp",
//     ],
//   },
//   {
//     id: 19,
//     toggle: false,
//     name: "Silver Charm Bracelet",
//     price: 18500,
//     originalPrice: 37000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-3.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-4.webp",
//     categorie: "Bracelets",
//     title: "Silver Charm Bracelet with Delicate Engravings for a Trendy Appeal",
//     tag: "New Arrival",
//     classic: false,
//         createdAt: "2024-04-18", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-3.webp",
//       "/img/dimondProdcut/braclets/braclet-4.webp",
//       "/img/dimondProdcut/braclets/braclet-3.webp",
//     ],
//   },

//   {
//     id: 20,
//     toggle: false,
//     name: "Platinum Cuff Bracelet",
//     price: 60000,
//     originalPrice: 120000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-4.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-5.webp",
//     categorie: "Bracelets",
//     title: "Platinum Cuff Bracelet with a Bold and Modern Appeal",
//     tag: "New Arrival",
//     classic: false,
//         createdAt: "2024-04-18", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-4.webp",
//       "/img/dimondProdcut/braclets/braclet-5.webp",
//       "/img/dimondProdcut/braclets/braclet-4.webp",
//     ],
//   },
//   {
//     id: 21,
//     toggle: false,
//     name: "Ruby-Studded Bracelet",
//     price: 49500,
//     originalPrice: 99000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-5.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-6.webp",
//     categorie: "Bracelets",
//     title: "Elegant Ruby-Studded Bracelet with a Royal Aesthetic",
//     tag: "New Arrival",

//         createdAt: "2024-04-18", // Added createdAt field

//     classic: false,
//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-5.webp",
//       "/img/dimondProdcut/braclets/braclet-6.webp",
//       "/img/dimondProdcut/braclets/braclet-5.webp",
//     ],
//   },
//   {
//     id: 22,
//     toggle: false,
//     name: "Sapphire Tennis Bracelet",
//     price: 68000,
//     originalPrice: 136000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-6.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-7.webp",
//     categorie: "Bracelets",
//     title: "Sapphire Tennis Bracelet Designed for Luxury and Sophistication",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-6.webp",
//       "/img/dimondProdcut/braclets/braclet-7.webp",
//       "/img/dimondProdcut/braclets/braclet-6.webp",
//     ],
//   },
//   {
//     id: 23,
//     toggle: false,
//     name: "Emerald Beaded Bracelet",
//     price: 32000,
//     originalPrice: 64000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-7.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-8.webp",
//     categorie: "Bracelets",
//     title: "Emerald Beaded Bracelet with a Unique and Trendy Look",
//     tag: "Best Seller",
//     classic: false,    createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclet-7.webp",
//       "/img/dimondProdcut/braclet-8.webp",
//       "/img/dimondProdcut/braclet-7.webp",
//     ],
//   },
//   {
//     id: 24,
//     toggle: false,
//     name: "Infinity Knot Bracelet",
//     price: 27000,
//     originalPrice: 54000,
//     discount: "50",
//     img1: "/img/dimondProdcut/braclets/braclet-8.webp",
//     img2: "/img/dimondProdcut/braclets/braclet-.webp",
//     categorie: "Bracelets",
//     title: "Infinity Knot Bracelet Symbolizing Eternal Love and Strength",
//     tag: "Best Seller",
//     classic: false,    createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/braclets/braclet-8.webp",
//       "/img/dimondProdcut/braclets/braclet-7.webp",
//       "/img/dimondProdcut/braclets/braclet-8.webp",
//     ],
//   },

//   {
//     id: 25,
//     toggle: false,
//     name: "Traditional Gold Bangles",
//     price: 68000,
//     originalPrice: 136000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-1.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-2.webp",
//     categorie: "Bangles",
//     title:
//       "Traditional Gold Bangles with an Ethnic Touch, Perfect for Festive Wear",
//     tag: "New Arrival",
//     classic: true,    createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-1.webp",
//       "/img/dimondProdcut/bangles/bangle-2.webp",
//       "/img/dimondProdcut/bangles/bangle-1.webp",
//     ],
//   },
//   {
//     id: 26,
//     toggle: false,
//     name: "Diamond Studded Bangles",
//     price: 75000,
//     originalPrice: 150000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-2.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-3.webp",
//     categorie: "Bangles",
//     title:
//       "Diamond Studded Bangles for a Royal Look, Blending Tradition with Luxury",
//     tag: "Best Seller",
//     classic: true,    createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-2.webp",
//       "/img/dimondProdcut/bangles/bangle-3.webp",
//       "/img/dimondProdcut/bangles/bangle-2.webp",
//     ],
//   },

//   {
//     id: 27,
//     toggle: false,
//     name: "Antique Bangles",
//     price: 49000,
//     originalPrice: 98000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-3.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-4.webp",
//     categorie: "Bangles",
//     title:
//       "Antique Bangles with an Old-World Charm, Showcasing Fine Craftsmanship",
//     tag: "Special Offer",
//     classic: true,    createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-3.webp",
//       "/img/dimondProdcut/bangles/bangle-4.webp",
//       "/img/dimondProdcut/bangles/bangle-3.webp",
//     ],
//   },
//   {
//     id: 28,
//     toggle: false,
//     name: "Kundan Bangles",
//     price: 72000,
//     originalPrice: 144000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-4.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-5.webp",
//     categorie: "Bangles",
//     title:
//       "Kundan Bangles with Intricate Detailing, Perfect for Grand Occasions",
//     tag: "New Arrival",
//     classic: true,   
//      createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-4.webp",
//       "/img/dimondProdcut/bangles/bangle-5.webp",
//       "/img/dimondProdcut/bangles/bangle-4.webp",
//     ],
//   },
//   {
//     id: 29,
//     toggle: false,
//     name: "Platinum Bangles",
//     price: 85000,
//     originalPrice: 170000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-5.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-6.webp",
//     categorie: "Bangles",
//     title: "Modern Platinum Bangles Offering a Sleek and Sophisticated Look",
//     tag: "Best Seller",
//     classic: true,  
//       createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-5.webp",
//       "/img/dimondProdcut/bangles/bangle-6.webp",
//       "/img/dimondProdcut/bangles/bangle-5.webp",
//     ],
//   },
//   {
//     id: 30,
//     toggle: false,
//     name: "Ruby-Embedded Bangles",
//     price: 65000,
//     originalPrice: 130000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-6.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-7.webp",
//     categorie: "Bangles",
//     title: "Ruby-Embedded Bangles with a Regal Design, Enhancing Elegance",
//     tag: "Special Offer",
//     classic: true, 
//        createdAt: "2024-05-14", // Added createdAt field

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-6.webp",
//       "/img/dimondProdcut/bangles/bangle-7.webp",
//       "/img/dimondProdcut/bangles/bangle-6.webp",
//     ],
//   },
//   {
//     id: 31,
//     toggle: false,
//     name: "Silver Filigree Bangles",
//     price: 42000,
//     originalPrice: 84000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-7.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-8.webp",
//     categorie: "Bangles" , // Added createdAt field
//     createdAt: "2024-05-14", // Added createdAt field

//     title:
//       "Silver Filigree Bangles with Artistic Detailing, A Timeless Classic",
//     tag: "New Arrival",
//     classic: true,
//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-7.webp",
//       "/img/dimondProdcut/bangles/bangle-8.webp",
//       "/img/dimondProdcut/bangles/bangle-7.webp",
//     ],
//   },
 
//   {
//     id: 32,
//     toggle: false,
//     name: "Traditional Gold Bangles",
//     price: 68000,
//     originalPrice: 136000,
//     discount: "50",
//     img1: "/img/dimondProdcut/bangles/bangle-6.webp",
//     img2: "/img/dimondProdcut/bangles/bangle-7.webp",
//     categorie: "Bangles",
//     title:
//       "Traditional Gold Bangles with an Ethnic Touch, Perfect for Festive Wear",
//     tag: "Best Seller",
//     classic: true,
//     createdAt: "2024-07-14", 

//   inerimgList: [
//       "/img/dimondProdcut/bangles/bangle-8.webp",
//       "/img/dimondProdcut/bangles/bangle-7.webp",
//       "/img/dimondProdcut/bangles/bangle-8.webp",
//     ],
//   },
  
//   {
//     id: 33,
//     toggle: false,
//     name: "Pearl Necklace",
//     price: 37000,
//     originalPrice: 74000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-1.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-2.webp",
//     categorie: "Necklace",
//     title: "Pearl Necklace with a Graceful Finish, Ideal for a Classic Look",
//     tag: "Best Seller",
//     classic: true,
//     createdAt: "2024-01-12", 

//   inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-1.webp",
//       "/img/dimondProdcut/neckles/neckles-2.webp",
//       "/img/dimondProdcut/neckles/neckles-1.webp",
//     ],
//   },
//   {
//     id: 34,
//     toggle: false,
//     name: "Gold Chain Necklace",
//     price: 52000,
//     originalPrice: 104000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-2.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-3.webp",
//     categorie: "Necklace",
//     title:
//       "Gold Chain Necklace with a Sleek and Modern Design for Everyday Wear",
//     tag: "Best Seller",
//     classic: true,
//     createdAt: "2024-01-12", 

//   inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-2.webp",
//       "/img/dimondProdcut/neckles/neckles-3.webp",
//       "/img/dimondProdcut/neckles/neckles-2.webp",
//     ],
//   },
//   {
//     id: 35,
//     toggle: false,
//     name: "Diamond Necklace",
//     price: 85000,
//     originalPrice: 170000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-3.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-4.webp",
//     categorie: "Necklace",
//     title:
//       "Diamond Necklace with a Luxurious Look, Perfect for Grand Occasions",
//     tag: "New Arrival",
//     classic: true,
//     createdAt: "2024-01-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-3.webp",
//       "/img/dimondProdcut/neckles/neckles-4.webp",
//       "/img/dimondProdcut/neckles/neckles-3.webp",
//     ],
//   },
//   {
//     id: 36,
//     toggle: false,
//     name: "Kundan Bridal Necklace",
//     price: 98000,
//     originalPrice: 196000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-4.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-5.webp",
//     categorie: "Necklace",
//     title: "Kundan Bridal Necklace with an Exquisite and Traditional Design",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-4.webp",
//       "/img/dimondProdcut/neckles/neckles-5.webp",
//       "/img/dimondProdcut/neckles/neckles-4.webp",
//     ],
//   },
//   {
//     id: 37,
//     toggle: false,
//     name: "Emerald Pendant Necklace",
//     price: 65000,
//     originalPrice: 130000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-5.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-6.webp",
//     categorie: "Necklace",
//     title: "Emerald Pendant Necklace, Offering a Rich and Royal Appeal",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-5.webp",
//       "/img/dimondProdcut/neckles/neckles-6.webp",
//       "/img/dimondProdcut/neckles/neckles-5.webp",
//     ],
//   },
//   {
//     id: 38,
//     toggle: false,
//     name: "Platinum Choker Necklace",
//     price: 72000,
//     originalPrice: 144000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-6.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-.webp",
//     categorie: "Necklace",
//     title: "Platinum Choker Necklace with a Contemporary yet Elegant Design",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-6.webp",
//       "/img/dimondProdcut/neckles/neckles-7.webp",
//       "/img/dimondProdcut/neckles/neckles-6.webp",
//     ],
//   },
//   {
//     id: 39,
//     toggle: false,
//     name: "Sapphire Drop Necklace",
//     price: 79000,
//     originalPrice: 158000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-7.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-8.webp",
//     categorie: "Necklace",
//     title: "Sapphire Drop Necklace with a Stunning and Radiant Finish",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-7.webp",
//       "/img/dimondProdcut/neckles/neckles-8.webp",
//       "/img/dimondProdcut/neckles/neckles-7.webp",
//     ],
//   },
//   {
//     id: 40,
//     toggle: false,
//     name: "Ruby Studded Necklace",
//     price: 89000,
//     originalPrice: 178000,
//     discount: "50",
//     img1: "/img/dimondProdcut/neckles/neckles-8.webp",
//     img2: "/img/dimondProdcut/neckles/neckles-5.webp",
//     categorie: "Necklace",
//     title: "Ruby Studded Necklace, A Statement Piece for Special Occasions",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/neckles/neckles-8.webp",
//       "/img/dimondProdcut/neckles/neckles-7.webp",
//       "/img/dimondProdcut/neckles/neckles-8.webp",
//     ],
//   },
//   {
//     id: 41,
//     toggle: false,
//     name: "Stud Earrings",
//     price: 21000,
//     originalPrice: 42000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-1.webp",
//     img2: "/img/dimondProdcut/earings/earing-2.webp",
//     categorie: "Earrings",
//     title: "Stud Earrings with a Simple Yet Elegant Design for a Chic Look",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-1.webp",
//       "/img/dimondProdcut/earings/earing-2.webp",
//       "/img/dimondProdcut/earings/earing-1.webp",
//     ],
//   },
//   {
//     id: 42,
//     toggle: false,
//     name: "Hoop Earrings",
//     price: 27500,
//     originalPrice: 55000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-2.webp",
//     img2: "/img/dimondProdcut/earings/earing-3.webp",
//     categorie: "Earrings",
//     title:
//       "Hoop Earrings with a Bold and Stylish Appearance, Perfect for Parties",
//     tag: "Special Offer",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-2.webp",
//       "/img/dimondProdcut/earings/earing-3.webp",
//       "/img/dimondProdcut/earings/earing-2.webp",
//     ],
//   },
//   {
//     id: 43,
//     toggle: false,
//     name: "Dangle Earrings",
//     price: 36000,
//     originalPrice: 72000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-3.webp",
//     img2: "/img/dimondProdcut/earings/earing-4.webp",
//     categorie: "Earrings",
//     title:
//       "Dangle Earrings with an Eye-Catching Shine for an Elegant Statement",
//     tag: "New Arrival",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-3.webp",
//       "/img/dimondProdcut/earings/earing-4.webp",
//       "/img/dimondProdcut/earings/earing-3.webp",
//     ],
//   },
//   {
//     id: 44,
//     toggle: false,
//     name: "Chandelier Earrings",
//     price: 48000,
//     originalPrice: 96000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-4.webp",
//     img2: "/img/dimondProdcut/earings/earing-5.webp",
//     categorie: "Earrings",
//     title: "Chandelier Earrings with Intricate Detailing, Perfect for Weddings",
//     tag: "Best Seller",
//     createdAt: "2024-05-12", 
//     classic: false,
//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-4.webp",
//       "/img/dimondProdcut/earings/earing-5.webp",
//       "/img/dimondProdcut/earings/earing-4.webp",
//     ],

//   },
//   {
//     id: 45,
//     toggle: false,
//     name: "Pearl Drop Earrings",
//     price: 32000,
//     originalPrice: 64000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-5.webp",
//     img2: "/img/dimondProdcut/earings/earing-6.webp",
//     categorie: "Earrings",
//     title: "Pearl Drop Earrings with a Soft and Elegant Look for Formal Wear",
//     tag: "New Arrival",
//     createdAt: "2024-04-12", 

//     classic: false,
//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-5.webp",
//       "/img/dimondProdcut/earings/earing-6.webp",
//       "/img/dimondProdcut/earings/earing-5.webp",
//     ],
//   },
//   {
//     id: 46,
//     toggle: false,
//     name: "Gold Huggie Earrings",
//     price: 28500,
//     originalPrice: 57000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-6.webp",
//     img2: "/img/dimondProdcut/earings/earing-7.webp",
//     categorie: "Earrings",
//     title: "Gold Huggie Earrings Offering a Modern and Minimalist Appeal",
//     tag: "Best Seller",
//     classic: false,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-6.webp",
//       "/img/dimondProdcut/earings/earing-7.webp",
//       "/img/dimondProdcut/earings/earing-6.webp",
//     ],
//   },
//   {
//     id: 47,
//     toggle: false,
//     name: "Diamond Cluster Earrings",
//     price: 75000,
//     originalPrice: 150000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-7.webp",
//     img2: "/img/dimondProdcut/earings/earing-8.webp",
//     categorie: "Earrings",
//     title: "Diamond Cluster Earrings with a Sparkling and Luxurious Touch",
//     tag: "Special Offer",
//     classic: true,
//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-7.webp",
//       "/img/dimondProdcut/earings/earing-8.webp",
//       "/img/dimondProdcut/earings/earing-7.webp",
//     ],
//   },
//   {
//     id: 48,
//     toggle: false,
//     name: "Sapphire Stud Earrings",
//     price: 43000,
//     originalPrice: 86000,
//     discount: "50",
//     img1: "/img/dimondProdcut/earings/earing-8.webp",
//     img2: "/img/dimondProdcut/earings/earing-7.webp",
//     categorie: "Earrings",
//     title: "Sapphire Stud Earrings Adding a Pop of Color to Any Outfit",
//     tag: "New Arrival",
//     classic: true,
//     createdAt: "2024-05-12", 

//     inerimgList: [
//       "/img/dimondProdcut/earings/earing-8.webp",
//       "/img/dimondProdcut/earings/earing-7.webp",
//       "/img/dimondProdcut/earings/earing-8.webp",
//     ],
//   },
// ];

// export default list;
